<?php

namespace App\Http\Resources;

use \Illuminate\Http\Request;
use JetBrains\PhpStorm\ArrayShape;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Resources\Json\ResourceCollection;

/**
 * @OA\Schema(
 *     title="IndexAchievementResource",
 *     description="Achievement resource",
 *     @OA\Xml(
 *         name="IndexAchievementResource"
 *     ),
 *     @OA\Property(
 *         title="meta",
 *         description="Pagination metadata",
 *         property="meta",
 *         type="object",
 *             @OA\Property(
 *                 title="page",
 *                 description="Page number",
 *                 type="integer",
 *                 property="page",
 *                 format="int64",
 *                 example=1
 *            ),
 *            @OA\Property(
 *                 title="per-page",
 *                 description="Number of entries per page",
 *                 type="integer",
 *                 property="per-page",
 *                 format="int64",
 *                 example=10
 *            )
 *     ),
 *     @OA\Property(
 *         title="data",
 *         description="Data wrapper",
 *         property="data",
 *         type="array",
 *         @OA\Items(type="object",
 *             @OA\Property(
 *                 title="id",
 *                 description="id",
 *                 type="integer",
 *                 property="id",
 *                 format="int64",
 *                 example=1
 *             ),
 *             @OA\Property(
 *                 title="Name",
 *                 description="Name of the new achievement",
 *                 example="A nice achievement",
 *                 type="string",
 *                 property="name",
 *             ),
 *             @OA\Property(
 *                 title="Slug",
 *                 description="Slug of the new achievement. Is autogenerated from name if not pass",
 *                 example="a-nice-achievement",
 *                 type="string",
 *                 property="slug"
 *             ),
 *             @OA\Property(
 *                 title="Description",
 *                 description="Description of the new achievement",
 *                 example="This is new achievement's description",
 *                 type="string",
 *                 property="description"
 *             ),
 *             @OA\Property(
 *                 title="Expression",
 *                 description="Language expression of the new achievement",
 *                 example="exercise.taskResults.countWithCondition('assessment', 10)",
 *                 type="string",
 *                 property="expression"
 *             ),
 *             @OA\Property(
 *                 title="Created at",
 *                 description="Created at",
 *                 example="2020-01-27 17:50:45",
 *                 format="datetime",
 *                 type="string",
 *                 property="created_at"
 *             ),
 *             @OA\Property(
 *                 title="Updated at",
 *                 description="Created at",
 *                 example="2020-01-27 17:50:45",
 *                 format="datetime",
 *                 type="string",
 *                 property="updated_at"
 *             )
 *         )
 *     )
 * )
 */
class AchievementCollection extends ResourceCollection
{
    public const PER_PAGE = 10;
    public const PAGE = 1;

    /**
     * @var int
     */
    private int $page;

    /**
     * @var int
     */
    private int $perPage;

    /**
     * AchievementCollection constructor.
     *
     * @param Collection $achievements
     * @param int $page
     * @param int $perPage
     */
    public function __construct(Collection $achievements, int $page, int $perPage)
    {
        parent::__construct($achievements);
        $this->page = $page;
        $this->perPage = $perPage;
    }

    /**
     * @param Request $request
     *
     * @return array
     */
    #[ArrayShape(['meta' => "array", 'data' => "\Illuminate\Support\Collection"])]
    public function toArray($request): array
    {
        return [
            'meta' => [
                'page' => $this->page,
                'per-page' => $this->perPage
            ],
            'data' => $this->collection,
        ];
    }
}
