<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use JetBrains\PhpStorm\ArrayShape;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @OA\Schema(
 *     title="AchievementResource",
 *     description="Achievement resource",
 *     @OA\Xml(
 *         name="AchievementResource"
 *     ),
 *
 *    @OA\Property(
 *           title="id",
 *           description="id",
 *           type="integer",
 *           property="id",
 *           format="int64",
 *           example=1
 *       ),
 *       @OA\Property(
 *           title="Name",
 *           description="Name of the new achievement",
 *           example="A nice achievement",
 *           type="string",
 *           property="name",
 *       ),
 *       @OA\Property(
 *           title="Slug",
 *           description="Slug of the new achievement. Is autogenerated from name if not pass",
 *           example="a-nice-achievement",
 *           type="string",
 *           property="slug"
 *       ),
 *       @OA\Property(
 *           title="Description",
 *           description="Description of the new achievement",
 *           example="This is new achievement's description",
 *           type="string",
 *           property="description"
 *       ),
 *       @OA\Property(
 *           title="Expression",
 *           description="Language expression of the new achievement",
 *           example="exercise.taskResults.countWithCondition('assessment', 10)",
 *           type="string",
 *           property="expression"
 *       ),
 *       @OA\Property(
 *           title="Created at",
 *           description="Created at",
 *           example="2020-01-27 17:50:45",
 *           format="datetime",
 *           type="string",
 *           property="created_at"
 *       ),
 *       @OA\Property(
 *           title="Updated at",
 *           description="Created at",
 *           example="2020-01-27 17:50:45",
 *           format="datetime",
 *           type="string",
 *           property="updated_at"
 *     )
 * )
 */
class AchievementResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  Request  $request
     * @return array
     */
    #[ArrayShape(['id' => 'mixed', 'name' => "mixed", 'slug' => "mixed", 'description' => "mixed", 'expression' => "mixed", 'created_at' => "mixed", 'updated_at' => "mixed"])]
    public function toArray($request): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'slug' => $this->slug,
            'description' => $this->description,
            'expression' => $this->expression,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at
        ];
    }
}
